"""
uAgents `Model` payloads (Pydantic v1) for worker request/response.

session_id is a UUID generated by the orchestrator per request and echoed
back by workers so the response can be correlated with the waiting asyncio.Event.
"""

from typing import List, Optional

from uagents import Model


class PartsSourcingRequest(Model):
    """Orchestrator → parts worker."""
    part_name: str
    part_number: str
    context_text: str
    session_id: str = ""


class PartSource(Model):
    """Single price source returned inside PartsSourcingResponse."""
    source_site: str
    price_usd: float
    purchase_url: str
    stock_status: str


class PartsSourcingResponse(Model):
    price_usd: float
    purchase_url: str
    stock_status: str
    source_site: str
    all_sources: List[PartSource] = []
    excel_path: str = ""
    session_id: str = ""  # echoed from request


class TutorialSearchRequest(Model):
    """Orchestrator → tutorial worker."""
    search_query: str
    session_id: str = ""


class TutorialSearchResponse(Model):
    video_url: str
    video_title: str
    duration_seconds: int = 0
    session_id: str = ""  # echoed from request


# Retained for HTTP/tests
class UserDiagnosticRequest(Model):
    image_url: Optional[str] = None
    image_base64: Optional[str] = None
    context_text: str = ""
    session_id: Optional[str] = None
